// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffruftopfwwhlzznwgrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmcnVmdG9wZnd3aGx6em53Z3J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0Njg1MDAsImV4cCI6MjA3MzA0NDUwMH0.OUbpipc1fvl9uXmc_3S3cEuUjsdQKnBgRwWIO_IpPJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});